version: '3.8'

services:
  # ========================================
  # BANCO DE DADOS LOCAL
  # ========================================
  postgres:
    image: postgres:15
    container_name: eralearn-postgres
    environment:
      POSTGRES_DB: eralearn
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    networks:
      - eralearn-network
    restart: unless-stopped

  # ========================================
  # NGINX PARA SERVER ARQUIVOS
  # ========================================
  nginx:
    image: nginx:alpine
    container_name: eralearn-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
      - ./branding:/var/www/branding
      - ./videos:/var/www/videos
      - ./public:/var/www/public
    networks:
      - eralearn-network
    depends_on:
      - postgres
    restart: unless-stopped

  # ========================================
  # SERVIDOR DE UPLOAD LOCAL
  # ========================================
  upload-server:
    build: ./server
    container_name: eralearn-upload
    ports:
      - "3001:3001"
    environment:
      - VIDEO_LOCAL_DIR=/var/www/videos
      - VIDEO_PUBLIC_BASE=/media/videos
      - VIDEO_MAX_UPLOAD_MB=1024
      - BRANDING_LOCAL_DIR=/var/www/branding
      - BRANDING_PUBLIC_BASE=/media/branding
    volumes:
      - ./videos:/var/www/videos
      - ./branding:/var/www/branding
    networks:
      - eralearn-network
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - upload-local

  # ========================================
  # FRONTEND (APLICAÇÃO PRINCIPAL)
  # ========================================
  eralearn:
    build: .
    container_name: eralearn-app
    ports:
      - "8080:8080"
    environment:
      # Configurações do banco local
      - VITE_SUPABASE_URL=http://localhost:5432
      - VITE_SUPABASE_ANON_KEY=local-key
      - DATABASE_URL=postgresql://admin:senha123@postgres:5432/eralearn
      
      # Configurações de upload local
      - VITE_VIDEO_UPLOAD_TARGET=local
      - VITE_VIDEO_MAX_UPLOAD_MB=1024
      - VITE_BRANDING_UPLOAD_TARGET=local
      
      # URLs locais
      - VITE_API_BASE_URL=http://localhost:3001
      - VITE_STORAGE_BASE_URL=http://localhost
    volumes:
      - ./uploads:/var/www/uploads
      - ./branding:/var/www/branding
      - ./videos:/var/www/videos
    networks:
      - eralearn-network
    depends_on:
      - postgres
      - nginx
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  eralearn-network:
    driver: bridge
























