version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: supabase/postgres:15.1.1.117
    container_name: supabase_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supabase_network

  # Supabase Studio
  studio:
    image: supabase/studio:20240115-0c7c9d1
    container_name: supabase_studio
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: your-super-secret-and-long-postgres-password
    depends_on:
      - postgres
      - meta
    networks:
      - supabase_network

  # PostgREST API
  postgrest:
    image: postgrest/postgrest:v11.2.0
    container_name: supabase_postgrest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: postgresql://postgres:your-super-secret-and-long-postgres-password@postgres:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
    depends_on:
      - postgres
    networks:
      - supabase_network

  # Storage API
  storage:
    image: supabase/storage-api:v0.40.4
    container_name: supabase_storage
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      PROJECT_REF: local
      POSTGREST_URL: http://postgrest:3000
      PGRST_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      DATABASE_URL: postgresql://postgres:your-super-secret-and-long-postgres-password@postgres:5432/postgres
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - storage_data:/var/lib/storage
    depends_on:
      - postgres
      - postgrest
    networks:
      - supabase_network

  # Auth API
  auth:
    image: supabase/gotrue:v2.132.3
    container_name: supabase_auth
    restart: unless-stopped
    ports:
      - "9999:9999"
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgresql://postgres:your-super-secret-and-long-postgres-password@postgres:5432/postgres?search_path=auth
      GOTRUE_SITE_URL: http://localhost:8080
      GOTRUE_URI_ALLOW_LIST: http://localhost:8080,http://localhost:3000
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_SECRET: your-super-secret-jwt-token-with-at-least-32-characters-long
      GOTRUE_MAILER_AUTOCONFIRM: "true"
    depends_on:
      - postgres
    networks:
      - supabase_network

  # Meta API
  meta:
    image: supabase/postgres-meta:v0.68.0
    container_name: supabase_meta
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: postgres
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: your-super-secret-and-long-postgres-password
    depends_on:
      - postgres
    networks:
      - supabase_network

volumes:
  postgres_data:
  storage_data:

networks:
  supabase_network:
    driver: bridge
